apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami
  name: whoami-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: whoami
  type: NodePort